import type { Venue } from "./types";

/** Static stadium data keyed by football-data.org team ID.
 *  football-data.org free tier doesn't provide coordinates, so we maintain this manually.
 */
export const VENUE_MAP: Record<number, Venue> = {
  // Premier League
  57: {
    id: "emirates-stadium",
    name: "Emirates Stadium",
    city: "London",
    citySlug: "london",
    address: "Highbury, London N5 1BU",
    lat: 51.5549,
    lng: -0.1084,
    capacity: 60704,
    airportCode: "LON",
    nearestStation: "Arsenal (Piccadilly line)",
    transportNote: "5-min walk from Arsenal tube. Also reachable from Highbury & Islington (Victoria line).",
    pubArea: "Highbury & Islington — try The Tollington or pubs on Upper Street.",
    fanPubs: [
      { name: "The Tollington", walkMins: 8, description: "Classic Arsenal local on Hornsey Road. Fills up early on matchday — get there 2 hours before kick-off." },
      { name: "Highbury Barn", walkMins: 12, description: "Gastropub on Highbury Park. Quieter and more relaxed than the spots near the tube — good for food too." },
      { name: "The Hen & Chickens", walkMins: 10, description: "Highbury Corner pub with a theatre upstairs. Lively pre-match atmosphere, home fans." },
    ],
    highlights: [
      { name: "Arsenal Museum & Stadium Tour", category: "experience", description: "Inside the Emirates — see trophies, shirts, and dressing rooms on a full stadium tour. Book in advance.", walkMins: 2 },
      { name: "Highbury Fields", category: "park", description: "Victorian park a short walk away. Good for a pre-match stroll and food from the café.", walkMins: 10 },
      { name: "Upper Street, Islington", category: "food", description: "One of London's best restaurant strips — everything from Lebanese to Japanese. 10 mins from the ground.", walkMins: 15 },
    ],
  },
  58: {
    id: "villa-park",
    name: "Villa Park",
    city: "Birmingham",
    citySlug: "birmingham",
    address: "Trinity Road, Birmingham B6 6HE",
    lat: 52.5092,
    lng: -1.8847,
    capacity: 42749,
    airportCode: "BHX",
    nearestStation: "Witton (train from New Street)",
    transportNote: "10-min train from Birmingham New Street to Witton, then a short walk.",
    pubArea: "Aston — plenty of pubs on Lichfield Road near the ground.",
    fanPubs: [
      { name: "The Villa Tavern", walkMins: 5, description: "Right on the walk from Witton station, packed on matchdays. Traditional Brummie pub." },
      { name: "The Aston Hotel", walkMins: 8, description: "Large pub near the Trinity Road end. Good for groups, home fans only on matchday." },
    ],
    highlights: [
      { name: "Jewellery Quarter", category: "shopping", description: "Birmingham's most distinctive neighbourhood — independent makers, cafes, and history.", walkMins: 30 },
      { name: "Cadbury World, Bournville", category: "experience", description: "The chocolate factory experience — great for a day trip before or after the match.", walkMins: 40 },
    ],
  },
  61: {
    id: "stamford-bridge",
    name: "Stamford Bridge",
    city: "London",
    citySlug: "london",
    address: "Fulham Road, London SW6 1HS",
    lat: 51.4816,
    lng: -0.191,
    capacity: 40343,
    airportCode: "LON",
    nearestStation: "Fulham Broadway (District line)",
    transportNote: "2-min walk from Fulham Broadway. Also reachable from Parsons Green.",
    pubArea: "Fulham Road & Kings Road — The Butcher's Hook and The Imperial Arms are the go-to pre-match spots.",
    fanPubs: [
      { name: "The Butcher's Hook", walkMins: 3, description: "The main pre-match pub for home fans, right on Fulham Road. Expect it to be rammed — arrive early." },
      { name: "The Imperial Arms", walkMins: 5, description: "Kings Road pub with a big beer garden. More relaxed than The Butcher's Hook, opens early on matchday." },
      { name: "The Finborough", walkMins: 8, description: "Smaller neighbourhood pub on Finborough Road. Good if you want to avoid the main crowds." },
    ],
    highlights: [
      { name: "Chelsea Physic Garden", category: "park", description: "Hidden walled garden founded in 1673 — London's oldest botanic garden. Open Sundays year-round.", walkMins: 15 },
      { name: "King's Road", category: "shopping", description: "Classic Chelsea shopping and people-watching. Stretch from Sloane Square to World's End.", walkMins: 5 },
      { name: "Natural History Museum", category: "museum", description: "Free entry, world-class collection. Worth arriving early on the day — in South Kensington, 15 mins by tube.", walkMins: 40 },
    ],
  },
  62: {
    id: "goodison-park",
    name: "Goodison Park",
    city: "Liverpool",
    citySlug: "liverpool",
    address: "Goodison Road, Liverpool L4 4EL",
    lat: 53.4388,
    lng: -2.9664,
    capacity: 39414,
    airportCode: "LPL",
    nearestStation: "Kirkdale (Merseyrail)",
    transportNote: "15-min walk from Lime Street, or short ride to Kirkdale on the Northern line.",
    pubArea: "Stanley Park area — The Winslow Hotel is the traditional pre-match pub.",
    fanPubs: [
      { name: "The Winslow Hotel", walkMins: 5, description: "The traditional Everton pre-match pub on Goodison Road. Atmospheric and very local." },
      { name: "The Thomas Frost", walkMins: 15, description: "Wetherspoons in the city centre — cheap, large, and accessible if you're arriving by train." },
    ],
    highlights: [
      { name: "Royal Albert Dock", category: "attraction", description: "Liverpool's iconic waterfront. Beatles Story, Tate Liverpool, and great food all in one place.", walkMins: 45 },
      { name: "Museum of Liverpool", category: "museum", description: "Free entry. Brilliant collection covering the city's culture, music, and football history.", walkMins: 45 },
    ],
  },
  63: {
    id: "craven-cottage",
    name: "Craven Cottage",
    city: "London",
    citySlug: "london",
    address: "Stevenage Road, London SW6 6HH",
    lat: 51.4749,
    lng: -0.2218,
    capacity: 29600,
    airportCode: "LON",
    nearestStation: "Putney Bridge (District line)",
    transportNote: "10-min walk from Putney Bridge along the Thames path.",
    pubArea: "Putney High Street — The Eight Bells is a popular pre-match stop.",
    fanPubs: [
      { name: "The Eight Bells", walkMins: 8, description: "Putney High Street stalwart. Busy on matchdays, usually mixed home and away." },
      { name: "The Rocket", walkMins: 5, description: "Large Wetherspoons in Putney — reliable option for big groups on a budget." },
    ],
    highlights: [
      { name: "Thames Riverside Walk", category: "park", description: "Walk the Thames path from Putney Bridge to the ground — one of the best approaches to any London stadium.", walkMins: 10 },
      { name: "Putney High Street", category: "food", description: "Good range of restaurants and cafes. Much less hectic than central London on matchday.", walkMins: 5 },
    ],
  },
  64: {
    id: "anfield",
    name: "Anfield",
    city: "Liverpool",
    citySlug: "liverpool",
    address: "Anfield Road, Liverpool L4 0TH",
    lat: 53.4308,
    lng: -2.9608,
    capacity: 61276,
    airportCode: "LPL",
    nearestStation: "Liverpool Lime Street (train)",
    transportNote: "Take bus 26 or 27 from the city centre, or it's a 40-min walk from Lime Street.",
    pubArea: "Anfield Road — The Albert is the most famous pre-match pub, right next to the ground.",
    fanPubs: [
      { name: "The Albert", walkMins: 2, description: "THE Anfield pub. Right opposite the main stand on Walton Breck Road. Legendary atmosphere, get there 2+ hours early." },
      { name: "The Sandon Hotel", walkMins: 5, description: "Historic pub on Oakfield Road — Liverpool FC was effectively founded here in 1892. Home fans, steeped in history." },
      { name: "The Arkles", walkMins: 6, description: "Popular matchday pub on Anfield Road. More space than The Albert, friendly atmosphere." },
    ],
    highlights: [
      { name: "LFC Museum & Stadium Tour", category: "experience", description: "Walk the Anfield pitch, see the trophy room, and visit the Boot Room. One of the best stadium tours in football.", walkMins: 2 },
      { name: "The Beatles Story", category: "museum", description: "Immersive Beatles museum at the Royal Albert Dock. A must if you're spending the day in Liverpool.", walkMins: 45 },
      { name: "Royal Albert Dock", category: "attraction", description: "Waterfront complex with world-class museums, bars, and restaurants. Spend a few hours here before heading to Anfield.", walkMins: 45 },
      { name: "Mathew Street", category: "food", description: "Beatles heartland — The Cavern Club and dozens of bars. Good for the night before or after an evening kick-off.", walkMins: 40 },
    ],
  },
  65: {
    id: "etihad-stadium",
    name: "Etihad Stadium",
    city: "Manchester",
    citySlug: "manchester",
    address: "Etihad Campus, Manchester M11 3FF",
    lat: 53.4831,
    lng: -2.2004,
    capacity: 53400,
    airportCode: "MAN",
    nearestStation: "Etihad Campus (Metrolink tram)",
    transportNote: "Direct tram from Manchester city centre — Etihad Campus stop is right outside.",
    pubArea: "Northern Quarter or Piccadilly Gardens — head in early, pubs near the ground are limited.",
    fanPubs: [
      { name: "The Mary D", walkMins: 10, description: "The main pre-match pub for City fans on Ashton New Road. Gets very busy — plan to arrive 2 hours before kick-off." },
      { name: "The Townley", walkMins: 12, description: "Closer to the stadium on Pottery Lane. Overflow option if The Mary D is full." },
      { name: "Northern Quarter pubs", walkMins: 45, description: "Manchester's best bar area — The Hare & Hounds, Alfie's, and dozens more. Better to drink here then tram over." },
    ],
    highlights: [
      { name: "National Football Museum", category: "museum", description: "Free entry. Housed in the stunning Urbis building in the city centre — covers the full history of English football.", walkMins: 50 },
      { name: "Northern Quarter", category: "food", description: "Manchester's creative neighbourhood — independent record shops, vintage stores, street food, and craft beer bars.", walkMins: 50 },
      { name: "Manchester Art Gallery", category: "museum", description: "Free entry. Strong pre-Raphaelite and modern British art collection in the city centre.", walkMins: 50 },
    ],
  },
  66: {
    id: "old-trafford",
    name: "Old Trafford",
    city: "Manchester",
    citySlug: "manchester",
    address: "Sir Matt Busby Way, Manchester M16 0RA",
    lat: 53.4631,
    lng: -2.2913,
    capacity: 74310,
    airportCode: "MAN",
    nearestStation: "Old Trafford (Metrolink tram)",
    transportNote: "Tram from Piccadilly to Old Trafford takes about 15 mins. Also accessible by train to Trafford Park.",
    pubArea: "Deansgate & Castlefield — good for pre-match drinks before making the trip to the ground.",
    fanPubs: [
      { name: "The Trafford", walkMins: 5, description: "Closest decent pub to Old Trafford on Chester Road. Popular with home fans on matchday." },
      { name: "The Bishops Blaize", walkMins: 8, description: "Well-known matchday pub on Chester Road, lively atmosphere before and after." },
      { name: "Deansgate Locks", walkMins: 40, description: "Manchester's bar and restaurant strip. Better to spend time here then tram over to Old Trafford." },
    ],
    highlights: [
      { name: "Manchester United Museum & Stadium Tour", category: "experience", description: "One of the world's most visited football museums. Theatre of Dreams tour includes the pitch, dressing rooms, and trophy room.", walkMins: 2 },
      { name: "The Lowry", category: "museum", description: "Gallery and theatre at Salford Quays — free galleries, excellent café. A 10-min tram from Old Trafford.", walkMins: 20 },
      { name: "MediaCityUK", category: "attraction", description: "BBC and ITV studios at Salford Quays. Tours available, or just walk around the waterfront.", walkMins: 20 },
      { name: "Castlefield", category: "park", description: "Roman fort ruins, canals, and outdoor bars — the best area in central Manchester on a sunny day.", walkMins: 40 },
    ],
  },
  67: {
    id: "st-james-park",
    name: "St James' Park",
    city: "Newcastle",
    citySlug: "newcastle",
    address: "St James' Park, Newcastle NE1 4ST",
    lat: 54.9756,
    lng: -1.6218,
    capacity: 52305,
    airportCode: "NCL",
    nearestStation: "St James' (Metro)",
    transportNote: "St James' Metro station is right next to the stadium — a 2-min walk.",
    pubArea: "Newcastle city centre — the Bigg Market and Grey Street have dozens of pre-match pubs.",
    fanPubs: [
      { name: "The Strawberry", walkMins: 2, description: "THE Newcastle pub. Right next to the Gallowgate End — iconic, raucous, and unmissable. Get there early.", awayFriendly: false },
      { name: "The Trent House", walkMins: 5, description: "Leazes Lane local, close to the stadium. Friendly atmosphere, real ales, and less chaotic than The Strawberry.", awayFriendly: true },
      { name: "Crown Posada", walkMins: 20, description: "One of Newcastle's oldest and most beautiful pubs — narrow, Victorian, brilliant. On The Side near the Quayside.", awayFriendly: true },
    ],
    highlights: [
      { name: "Newcastle Quayside", category: "attraction", description: "The Tyne bridges, BALTIC art gallery, and The Sage Gateshead — walk across the Millennium Bridge for the best view.", walkMins: 20 },
      { name: "BALTIC Centre for Contemporary Art", category: "museum", description: "Free entry. Converted flour mill on the Gateshead side — internationally recognised contemporary art.", walkMins: 25 },
      { name: "Grey Street & Grainger Town", category: "shopping", description: "Newcastle's Georgian heart — spectacular architecture, independent shops, and the covered Grainger Market.", walkMins: 15 },
      { name: "Castle Keep", category: "attraction", description: "The Norman castle that gave Newcastle its name. Climb the keep for panoramic city views.", walkMins: 20 },
    ],
  },
  73: {
    id: "tottenham-hotspur-stadium",
    name: "Tottenham Hotspur Stadium",
    city: "London",
    citySlug: "london",
    address: "782 High Road, London N17 0BX",
    lat: 51.6043,
    lng: -0.0665,
    capacity: 62850,
    airportCode: "LON",
    nearestStation: "White Hart Lane (train from Liverpool Street)",
    transportNote: "Train from Liverpool Street to White Hart Lane is the quickest route — about 30 mins.",
    pubArea: "High Road & Tottenham — The Bill Nicholson pub is the home fans' favourite.",
    fanPubs: [
      { name: "The Bill Nicholson", walkMins: 2, description: "The official Spurs pub right next to the stadium. Named after the legendary manager — expect a full house on matchday." },
      { name: "The Antwerp Arms", walkMins: 12, description: "The most historic Spurs pub, saved by fans from closure. Brilliant community local on Church Road N17. Worth the walk.", awayFriendly: true },
      { name: "The Bricklayers Arms", walkMins: 8, description: "Traditional local on Church Lane — less tourist-y than The Bill Nick, friendly atmosphere." },
    ],
    highlights: [
      { name: "Tottenham Hotspur Stadium Tour", category: "experience", description: "One of Europe's best modern stadium tours — includes NFL pitch, brewery, and rooftop walk.", walkMins: 2 },
      { name: "Alexandra Palace", category: "attraction", description: "The 'People's Palace' with stunning London views. Ice rink, regular events, and a great café.", walkMins: 30 },
      { name: "Bruce Castle Museum", category: "museum", description: "Free local history museum in a Tudor manor house — covers Tottenham and North London's history.", walkMins: 15 },
    ],
  },
  76: {
    id: "molineux",
    name: "Molineux Stadium",
    city: "Wolverhampton",
    citySlug: "wolverhampton",
    address: "Waterloo Road, Wolverhampton WV1 4QR",
    lat: 52.5901,
    lng: -2.1308,
    capacity: 32050,
    airportCode: "BHX",
    nearestStation: "Wolverhampton (train/tram)",
    transportNote: "10-min walk from Wolverhampton train station. Regular trains from Birmingham New Street.",
    pubArea: "Wolverhampton city centre — The Goalpost on Waterloo Road is popular pre-match.",
    fanPubs: [
      { name: "The Goalpost", walkMins: 5, description: "The main Wolves fan pub on Waterloo Road, a short walk from the ground. Gets busy — arrive early." },
      { name: "The Wanderer", walkMins: 8, description: "City-centre Wetherspoons — reliable option for a cheaper pre-match drink with good transport links." },
    ],
    highlights: [
      { name: "Wolverhampton Art Gallery", category: "museum", description: "Free entry. Strong pop art collection and local history — surprisingly good for a city this size.", walkMins: 15 },
    ],
  },
  338: {
    id: "king-power-stadium",
    name: "King Power Stadium",
    city: "Leicester",
    citySlug: "leicester",
    address: "Filbert Way, Leicester LE2 7FL",
    lat: 52.6204,
    lng: -1.1422,
    capacity: 32312,
    airportCode: "EMA",
    nearestStation: "Leicester (train)",
    transportNote: "25-min walk from Leicester station, or short taxi/bus ride.",
    pubArea: "Leicester city centre — the Golden Mile on Belgrave Road for food, or city-centre pubs.",
    fanPubs: [
      { name: "The Counting House", walkMins: 15, description: "Central Leicester Wetherspoons — busy on matchdays but easy to get to from the station." },
      { name: "The Local Hero", walkMins: 10, description: "Popular with Leicester fans on the walk to the ground from the city centre." },
    ],
    highlights: [
      { name: "King Richard III Visitor Centre", category: "museum", description: "Where Richard III's remains were found in a car park — a remarkable story, brilliantly told.", walkMins: 20 },
      { name: "Belgrave Road (Golden Mile)", category: "food", description: "Britain's best Indian restaurant street. Leicester's curry houses are world-famous — go after the match.", walkMins: 25 },
    ],
  },
  340: {
    id: "st-marys-stadium",
    name: "St Mary's Stadium",
    city: "Southampton",
    citySlug: "southampton",
    address: "Britannia Road, Southampton SO14 5FP",
    lat: 50.9058,
    lng: -1.3914,
    capacity: 32384,
    airportCode: "SOU",
    nearestStation: "Southampton Central (train)",
    transportNote: "15-min walk from Southampton Central station along the waterfront.",
    pubArea: "Oxford Street & Bedford Place — lively bar scene a short walk from the ground.",
    fanPubs: [
      { name: "The Southwestern Arms", walkMins: 10, description: "Well-regarded local pub in the Bedford Place area, popular with Saints fans before home games." },
    ],
    highlights: [
      { name: "SeaCity Museum", category: "museum", description: "Free entry. Covers the Titanic — Southampton was the ship's home port — and local maritime history.", walkMins: 20 },
      { name: "Southampton Old Town", category: "attraction", description: "Medieval walls, the old bargate, and the Tudor House — unexpected history in a modern city.", walkMins: 20 },
    ],
  },
  341: {
    id: "elland-road",
    name: "Elland Road",
    city: "Leeds",
    citySlug: "leeds",
    address: "Elland Road, Leeds LS11 0ES",
    lat: 53.7776,
    lng: -1.5722,
    capacity: 37890,
    airportCode: "LBA",
    nearestStation: "Leeds (train)",
    transportNote: "25-min walk from Leeds station, or take a matchday bus (service 51/52).",
    pubArea: "Beeston & city centre — The Old Peacock on Elland Road is the classic pre-match pub.",
    fanPubs: [
      { name: "The Old Peacock", walkMins: 3, description: "The most famous Leeds United pub — right outside the ground on Elland Road. The essential pre-match stop." },
      { name: "Calls Landing", walkMins: 35, description: "Riverside bar area in Leeds city centre — worth spending time here before the matchday bus." },
    ],
    highlights: [
      { name: "Leeds City Markets", category: "shopping", description: "Victorian covered market — great food hall, independent traders, and a real slice of Leeds life.", walkMins: 40 },
      { name: "Royal Armouries Museum", category: "museum", description: "Free entry. World-class collection of arms and armour, set in a striking building on the waterfront.", walkMins: 35 },
    ],
  },
  351: {
    id: "the-city-ground",
    name: "The City Ground",
    city: "Nottingham",
    citySlug: "nottingham",
    address: "Pavilion Road, Nottingham NG2 5FJ",
    lat: 52.94,
    lng: -1.1329,
    capacity: 30445,
    airportCode: "EMA",
    nearestStation: "Nottingham (train)",
    transportNote: "25-min walk from Nottingham station along the River Trent, or take tram to Meadows.",
    pubArea: "Lace Market & Hockley — great bar scene in the city centre, 30 mins before heading to the ground.",
    fanPubs: [
      { name: "The Southbank Bar", walkMins: 3, description: "Very close to the City Ground — the main pre-match pub for Forest fans." },
      { name: "The Embankment", walkMins: 8, description: "Victorian pub on the Trent embankment, popular on matchdays. Good views of the river." },
    ],
    highlights: [
      { name: "Nottingham Castle", category: "attraction", description: "Clifftop castle with caves, city views, and a museum. Recently restored and well worth visiting.", walkMins: 40 },
      { name: "Lace Market", category: "attraction", description: "Victorian lace warehouses converted into bars, restaurants, and galleries. The beating heart of Nottingham's nightlife.", walkMins: 35 },
    ],
  },
  354: {
    id: "selhurst-park",
    name: "Selhurst Park",
    city: "London",
    citySlug: "london",
    address: "Whitehorse Lane, London SE25 6PU",
    lat: 51.3983,
    lng: -0.0855,
    capacity: 25486,
    airportCode: "LON",
    nearestStation: "Selhurst (train from London Bridge)",
    transportNote: "2-min walk from Selhurst station. Trains from London Bridge or East Croydon.",
    pubArea: "Croydon town centre or The Clifton Arms on Whitehorse Lane near the ground.",
    fanPubs: [
      { name: "The Clifton Arms", walkMins: 3, description: "The traditional Crystal Palace pub near Selhurst Park. Home fans, busy on matchday." },
    ],
    highlights: [
      { name: "Crystal Palace Park", category: "park", description: "Victorian park with life-size dinosaur sculptures and the foundations of the original Crystal Palace.", walkMins: 20 },
    ],
  },
  397: {
    id: "amex-stadium",
    name: "Amex Stadium",
    city: "Brighton",
    citySlug: "brighton",
    address: "Village Way, Brighton BN1 9BL",
    lat: 50.8618,
    lng: -0.0838,
    capacity: 31876,
    airportCode: "LGW",
    nearestStation: "Falmer (train from Brighton)",
    transportNote: "Falmer station is a 5-min walk — direct trains from Brighton station (every 10 mins on matchday).",
    pubArea: "Brighton seafront & North Laine — enjoy the city before heading to Falmer. Pubs near the ground are limited.",
    fanPubs: [
      { name: "The Greys", walkMins: 60, description: "Brighton city centre pub popular with Seagulls fans before the train out to Falmer. Good atmosphere." },
      { name: "The Signalman", walkMins: 8, description: "Closest pub to Falmer station — the main option if you want a drink near the ground." },
    ],
    highlights: [
      { name: "Brighton Beach & Palace Pier", category: "attraction", description: "The iconic Brighton seafront — pebble beach, arcades, and fish & chips. Spend a few hours here first.", walkMins: 60 },
      { name: "North Laine", category: "shopping", description: "Brighton's bohemian quarter — vintage shops, record stores, independent cafes, and street art.", walkMins: 55 },
      { name: "Royal Pavilion", category: "attraction", description: "George IV's extraordinary Indian-Mughal palace in the heart of Brighton — one of England's most unique buildings.", walkMins: 55 },
    ],
  },
  402: {
    id: "gtech-community-stadium",
    name: "Gtech Community Stadium",
    city: "London",
    citySlug: "london",
    address: "Lionel Road North, Brentford TW8 0NT",
    lat: 51.4882,
    lng: -0.3086,
    capacity: 17250,
    airportCode: "LON",
    nearestStation: "Brentford (train from Waterloo)",
    transportNote: "5-min walk from Brentford station. Or take the Overground to Kew Bridge.",
    pubArea: "Brentford High Street — The Magpie & Crown is the traditional local. Also try the Waterman's Arts Centre.",
    fanPubs: [
      { name: "The Magpie & Crown", walkMins: 5, description: "Traditional Brentford local on the High Street — the spiritual home of pre-match Bees fans.", awayFriendly: true },
      { name: "The Express Tavern", walkMins: 10, description: "Victorian pub near the river — good ales, less crowded than the High Street spots.", awayFriendly: true },
    ],
    highlights: [
      { name: "Kew Gardens", category: "park", description: "The Royal Botanic Gardens — world-class, beautiful, and a 10-min walk across Kew Bridge. Book ahead.", walkMins: 20 },
      { name: "Syon House & Park", category: "attraction", description: "Robert Adam-designed house in riverside parkland. Great for a pre-match morning walk.", walkMins: 25 },
    ],
  },
  563: {
    id: "london-stadium",
    name: "London Stadium",
    city: "London",
    citySlug: "london",
    address: "Queen Elizabeth Olympic Park, London E20 2ST",
    lat: 51.5386,
    lng: -0.0163,
    capacity: 62500,
    airportCode: "LON",
    nearestStation: "Stratford (Central / Jubilee / Overground)",
    transportNote: "10-min walk from Stratford station — one of the best-connected grounds in the country.",
    pubArea: "Stratford Westfield for food & drinks pre-match, or Hackney Wick for a more local feel.",
    fanPubs: [
      { name: "Hackney Wick bars", walkMins: 25, description: "Artefact, Mick's Garage, and dozens of other independent venues in East London's creative hub. Worth the walk." },
      { name: "Westfield Stratford", walkMins: 12, description: "Shopping centre with many bars and restaurants — convenient but corporate. Okay if you need food before kick-off." },
    ],
    highlights: [
      { name: "Queen Elizabeth Olympic Park", category: "park", description: "Legacy of the 2012 Olympics — the Velodrome, Aquatics Centre, ArcelorMittal Orbit, and beautiful landscaped park.", walkMins: 5 },
      { name: "V&A East Storehouse", category: "museum", description: "Brand new V&A outpost in Stratford — opens 2025, right next to the stadium.", walkMins: 5 },
      { name: "Hackney Wick", category: "food", description: "East London's creative neighbourhood — canal-side bars, street food, artist studios, and live music.", walkMins: 25 },
    ],
  },
  // Championship
  328: {
    id: "turf-moor",
    name: "Turf Moor",
    city: "Burnley",
    citySlug: "burnley",
    address: "Harry Potts Way, Burnley BB10 4BX",
    lat: 53.7893,
    lng: -2.2309,
    capacity: 21944,
    airportCode: "MAN",
    nearestStation: "Burnley Central (train)",
    transportNote: "15-min walk from Burnley Central, or short taxi. Trains from Manchester Victoria.",
    pubArea: "Burnley town centre — The Talbot is near the ground; the town centre has plenty of options.",
    fanPubs: [
      { name: "The Talbot", walkMins: 8, description: "Well-known Burnley fan pub near Turf Moor. Traditional Lancashire pub, friendly atmosphere." },
    ],
    highlights: [
      { name: "Pendle Hill", category: "park", description: "Iconic Lancashire landmark and walking destination — stunning views over the Ribble Valley. 20 mins by car.", walkMins: 999 },
    ],
  },
  345: {
    id: "hillsborough",
    name: "Hillsborough Stadium",
    city: "Sheffield",
    citySlug: "sheffield",
    address: "Penistone Road, Sheffield S6 1SW",
    lat: 53.4118,
    lng: -1.5007,
    capacity: 39732,
    airportCode: "LBA",
    nearestStation: "Hillsborough (Supertram)",
    transportNote: "Take the Supertram from Sheffield city centre to Hillsborough — about 20 mins.",
    pubArea: "Hillsborough Corner — The Ball Inn and Hillsborough Hotel are popular pre-match.",
    fanPubs: [
      { name: "The Ball Inn", walkMins: 5, description: "Classic Sheffield Wednesday pub near the ground. Traditional atmosphere, busy on matchday." },
      { name: "The Hillsborough Hotel", walkMins: 3, description: "Right at Hillsborough Corner — the nearest big pub to the stadium." },
    ],
    highlights: [
      { name: "Kelham Island Museum", category: "museum", description: "Free entry. Sheffield's industrial history brought to life — the mighty River Don Engine runs on Fridays.", walkMins: 50 },
      { name: "Ecclesall Road", category: "food", description: "Sheffield's best pub and restaurant strip — excellent independent food scene.", walkMins: 40 },
    ],
  },
  356: {
    id: "bramall-lane",
    name: "Bramall Lane",
    city: "Sheffield",
    citySlug: "sheffield",
    address: "Cherry Street, Sheffield S2 4SU",
    lat: 53.3702,
    lng: -1.4708,
    capacity: 32050,
    airportCode: "LBA",
    nearestStation: "Sheffield (train)",
    transportNote: "20-min walk from Sheffield station, or take a tram to Cricket Inn Road.",
    pubArea: "Ecclesall Road — Sheffield's best pub strip is a short walk from Bramall Lane.",
    fanPubs: [
      { name: "The Cricketers Arms", walkMins: 5, description: "Traditional Blades pub near the ground — named after Bramall Lane's cricketing history." },
      { name: "The Sheaf View", walkMins: 10, description: "Excellent real ale pub close to Bramall Lane, popular with Sheffield United fans." },
    ],
    highlights: [
      { name: "Kelham Island Museum", category: "museum", description: "Free entry. One of the UK's best industrial museums — Sheffield's steel and cutlery heritage on show.", walkMins: 25 },
      { name: "Ecclesall Road", category: "food", description: "Sheffield's most celebrated pub and dining strip — great independents from breakfast to late.", walkMins: 20 },
    ],
  },
  387: {
    id: "ashton-gate",
    name: "Ashton Gate Stadium",
    city: "Bristol",
    citySlug: "bristol",
    address: "Ashton Road, Bristol BS3 2EJ",
    lat: 51.44,
    lng: -2.6202,
    capacity: 27000,
    airportCode: "BRS",
    nearestStation: "Bristol Temple Meads (train)",
    transportNote: "30-min walk from Temple Meads, or take the No. 24 bus from the city centre.",
    pubArea: "Bedminster & Southville — The Hen & Chicken and the North Street bar scene.",
    fanPubs: [
      { name: "The Hen & Chicken", walkMins: 10, description: "North Street institution with a theatre above — the pre-match favourite for City fans in Southville." },
      { name: "The Spotted Cow", walkMins: 12, description: "Friendly Bedminster local popular with Bristol City supporters on matchdays." },
    ],
    highlights: [
      { name: "Clifton Suspension Bridge", category: "attraction", description: "Brunel's iconic bridge over the Avon Gorge — walk across for free, stunning views.", walkMins: 40 },
      { name: "Harbourside", category: "food", description: "Bristol's waterfront — Watershed, Arnolfini, and dozens of bars and restaurants along the floating harbour.", walkMins: 35 },
      { name: "Stokes Croft", category: "food", description: "Bristol's bohemian neighbourhood — street art, independent cafes, Banksy territory.", walkMins: 40 },
    ],
  },
  715: {
    id: "cardiff-city-stadium",
    name: "Cardiff City Stadium",
    city: "Cardiff",
    citySlug: "cardiff",
    address: "Leckwith Road, Cardiff CF11 8AZ",
    lat: 51.4727,
    lng: -3.2033,
    capacity: 33280,
    airportCode: "CWL",
    nearestStation: "Ninian Park (train from Cardiff Central)",
    transportNote: "Short train from Cardiff Central to Ninian Park, or a 25-min walk.",
    pubArea: "Cardiff city centre — St Mary Street and the Victorian Arcade area for pre-match food and drinks.",
    fanPubs: [
      { name: "The Canton Cross", walkMins: 15, description: "Popular Canton pub on the walk from the city centre to the stadium — friendly atmosphere." },
    ],
    highlights: [
      { name: "Cardiff Castle", category: "attraction", description: "Norman castle in the heart of the city — ornate Victorian Gothic apartments inside, free grounds.", walkMins: 30 },
      { name: "Cardiff Bay", category: "attraction", description: "The Senedd, Wales Millennium Centre, and Roald Dahl Plass — great for a waterfront walk.", walkMins: 35 },
      { name: "The Victorian Arcades", category: "shopping", description: "Cardiff's famous covered arcades — Morgan Arcade, Royal Arcade — independent shops and cafes.", walkMins: 30 },
    ],
  },
  1044: {
    id: "vitality-stadium",
    name: "Vitality Stadium",
    city: "Bournemouth",
    citySlug: "bournemouth",
    address: "Dean Court, Bournemouth BH7 7AF",
    lat: 50.7352,
    lng: -1.8383,
    capacity: 11307,
    airportCode: "BOH",
    nearestStation: "Bournemouth (train)",
    transportNote: "20-min walk from Bournemouth station, or take the Yellow Buses service.",
    pubArea: "Boscombe & Bournemouth town centre — The Firkin Shed on Holdenhurst Road is the local favourite.",
    fanPubs: [
      { name: "The Firkin Shed", walkMins: 10, description: "Craft beer bar and the best pre-match option for Cherries fans near Dean Court." },
    ],
    highlights: [
      { name: "Bournemouth Beach", category: "park", description: "Seven miles of sandy beach — one of the best on the south coast. Good for a morning walk before the match.", walkMins: 25 },
      { name: "Poole Quay", category: "attraction", description: "Historic harbour town a short bus ride away — great seafood, one of the world's largest natural harbours.", walkMins: 45 },
    ],
  },
};

/** Away fan data keyed by home team ID — merged into venue on lookup. */
const AWAY_FAN_DATA: Partial<Record<number, Pick<import("./types").Venue, "awayStand" | "awayCapacity" | "ticketOfficeUrl">>> = {
  57:   { awayStand: "Clock End",                      awayCapacity: 3000, ticketOfficeUrl: "https://www.arsenal.com/tickets" },
  58:   { awayStand: "Doug Ellis Stand (Lower)",        awayCapacity: 3000, ticketOfficeUrl: "https://www.avfc.co.uk/tickets" },
  61:   { awayStand: "Shed End (Lower)",                awayCapacity: 2500, ticketOfficeUrl: "https://www.chelseafc.com/en/tickets" },
  62:   { awayStand: "Bullens Road Stand (Lower)",      awayCapacity: 2500, ticketOfficeUrl: "https://www.evertonfc.com/tickets" },
  63:   { awayStand: "Hammersmith End",                 awayCapacity: 2500, ticketOfficeUrl: "https://www.fulhamfc.com/tickets" },
  64:   { awayStand: "Anfield Road End",                awayCapacity: 3000, ticketOfficeUrl: "https://www.liverpoolfc.com/tickets" },
  65:   { awayStand: "South Stand (Colin Bell Stand)",  awayCapacity: 3000, ticketOfficeUrl: "https://www.mancity.com/tickets" },
  66:   { awayStand: "East Stand (Lower)",              awayCapacity: 3000, ticketOfficeUrl: "https://www.manutd.com/en/tickets" },
  67:   { awayStand: "Leazes End",                      awayCapacity: 3000, ticketOfficeUrl: "https://www.nufc.co.uk/tickets" },
  73:   { awayStand: "South Stand",                     awayCapacity: 3000, ticketOfficeUrl: "https://www.tottenhamhotspur.com/tickets" },
  76:   { awayStand: "Jack Harris Stand",               awayCapacity: 2500, ticketOfficeUrl: "https://www.wolves.co.uk/tickets" },
  338:  { awayStand: "Away End (East)",                 awayCapacity: 3000, ticketOfficeUrl: "https://www.lcfc.com/tickets" },
  341:  { awayStand: "South Stand (Lower)",             awayCapacity: 4000, ticketOfficeUrl: "https://www.leedsunited.com/tickets" },
  351:  { awayStand: "Bridgford Stand (Lower)",         awayCapacity: 3000, ticketOfficeUrl: "https://www.nottinghamforest.co.uk/tickets" },
  354:  { awayStand: "Arthur Wait Stand (Lower)",       awayCapacity: 2500, ticketOfficeUrl: "https://www.cpfc.co.uk/tickets" },
  397:  { awayStand: "North Stand (Upper)",             awayCapacity: 3000, ticketOfficeUrl: "https://www.brightonandhovealbion.com/tickets" },
  402:  { awayStand: "Away End (South)",                awayCapacity: 2000, ticketOfficeUrl: "https://www.brentfordfc.com/en/tickets" },
  563:  { awayStand: "East Stand (Upper)",              awayCapacity: 5000, ticketOfficeUrl: "https://www.whufc.com/tickets" },
  1044: { awayStand: "Away End",                        awayCapacity: 2000, ticketOfficeUrl: "https://www.afcb.co.uk/tickets" },
};

export function getVenueByTeamId(teamId: number): Venue | undefined {
  const venue = VENUE_MAP[teamId];
  if (!venue) return undefined;
  const awayData = AWAY_FAN_DATA[teamId];
  return awayData ? { ...venue, ...awayData } : venue;
}
